[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "lambdas"
version = "0.1.0"
description = "Typed lambdas that are short and readable"
license = "BSD-2-Clause"

authors = [
  "sobolevn <mail@sobolevn.me>"
]

readme = "README.md"

repository = "https://github.com/dry-python/lambdas"
homepage = "https://lambdas.readthedocs.io"

keywords = [
  "functional programming",
  "fp",
  "lambda",
  "lambdas",
  "composition",
  "type-safety",
  "mypy",
  "stubs"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.6"
typing-extensions = "^3.7"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
wemake-python-styleguide = "^0.15.2"
flake8-pytest = "^1.3"
flake8-pytest-style = "^1.5.0"
flake8-pyi = "^20.10"
nitpick = "^0.26.0"

safety = "^1.10"

pytest = "^6.2"
pytest-cov = "^2.12"
pytest-randomly = "^3.8"
pytest-mypy-plugins = "^1.7"

sphinx = "^4.0"
sphinx-autodoc-typehints = "^1.12"
sphinxcontrib-mermaid = "^0.7"
sphinx-typlog-theme = "^0.8.0"
doc8 = "^0.8.1"
m2r2 = "^0.2.7"
tomlkit = "^0.11.4"
